Update resetpassword.js
since the test@test,com is failed so i have to put my own email, the error was
 Error: We have blocked all requests from this device due to unusual activity. Try again later.